# Gruvbox Dark color theme for aerc
# https://github.com/morhetz/gruvbox

BG_BASE="#282828"
BG_ELEVATED="#3c3836"
BG_SELECTION="#3c3836"
BG_BORDER="#665c54"
FG_BASE="#ebdbb2"
FG_BRIGHT="#fbf1c7"
FG_BRIGHTEST="#fbf1c7"
FG_DIM="#928374"
ACCENT_PRIMARY="#83a598"
ACCENT_SECONDARY="#8ec07c"
ACCENT_TERTIARY="#8ec07c"
COLOR_ERROR="#fb4934"
COLOR_WARNING="#fe8019"
COLOR_SUCCESS="#b8bb26"
COLOR_INFO="#fabd2f"
COLOR_SPECIAL="#d3869b"

C_HEADING="$COLOR_SUCCESS bold"
C_BOLD="bold"
C_ITALIC="italic"
C_LINK_TEXT="$ACCENT_SECONDARY"
C_LINK_URL="$FG_DIM"
C_RULE="$FG_DIM"

# -- Header tokens --
C_HDR_KEY="$ACCENT_PRIMARY bold"
C_HDR_VALUE="$FG_BASE"
C_HDR_DIM="$FG_DIM"

# -- Picker tokens --
C_PICKER_NUM="$ACCENT_PRIMARY"
C_PICKER_LABEL="$FG_BASE"
C_PICKER_URL="$FG_DIM"
C_PICKER_SEL_BG="$BG_SELECTION"
C_PICKER_SEL_FG="$FG_BRIGHT"

# -- Message UI tokens (overlays and confirmations) --
C_MSG_MARKER="$FG_DIM bold"
C_MSG_TITLE_SUCCESS="$COLOR_SUCCESS bold"
C_MSG_TITLE_ACCENT="$ACCENT_PRIMARY bold"
C_MSG_DETAIL="$FG_BASE"
C_MSG_DIM="$FG_DIM"
