# Solarized Dark color theme for aerc
# https://ethanschoonover.com/solarized/

BG_BASE="#002b36"
BG_ELEVATED="#073642"
BG_SELECTION="#073642"
BG_BORDER="#586e75"
FG_BASE="#839496"
FG_BRIGHT="#93a1a1"
FG_BRIGHTEST="#eee8d5"
FG_DIM="#657b83"
ACCENT_PRIMARY="#268bd2"
ACCENT_SECONDARY="#2aa198"
ACCENT_TERTIARY="#2aa198"
COLOR_ERROR="#dc322f"
COLOR_WARNING="#cb4b16"
COLOR_SUCCESS="#859900"
COLOR_INFO="#b58900"
COLOR_SPECIAL="#6c71c4"

C_HEADING="$COLOR_SUCCESS bold"
C_BOLD="bold"
C_ITALIC="italic"
C_LINK_TEXT="$ACCENT_SECONDARY"
C_LINK_URL="$FG_DIM"
C_RULE="$FG_DIM"

# -- Header tokens --
C_HDR_KEY="$ACCENT_PRIMARY bold"
C_HDR_VALUE="$FG_BASE"
C_HDR_DIM="$FG_DIM"

# -- Picker tokens --
C_PICKER_NUM="$ACCENT_PRIMARY"
C_PICKER_LABEL="$FG_BASE"
C_PICKER_URL="$FG_DIM"
C_PICKER_SEL_BG="$BG_SELECTION"
C_PICKER_SEL_FG="$FG_BRIGHT"

# -- Message UI tokens (overlays and confirmations) --
C_MSG_MARKER="$FG_DIM bold"
C_MSG_TITLE_SUCCESS="$COLOR_SUCCESS bold"
C_MSG_TITLE_ACCENT="$ACCENT_PRIMARY bold"
C_MSG_DETAIL="$FG_BASE"
C_MSG_DIM="$FG_DIM"
